### ISSUE TITLE
Bad yaml configuration causes failure

### ISSUE THREAD

**Issue by shadowbq** [shadowbq/remote_syslog2#15]
```shell
2018-11-16 18:02:40 CRITICAL  nomnomlog.go:232 Failed to configure the application: 1 error(s) decoding:

* Invalid log file map[interface {}]interface {}{"tag":"abc"}
```

```yaml
files:
  - locallog.txt
  - tag: abc
```

**Comment by shadowbq** [comment]
So thats just bad yaml in the above example.

**Comment by shadowbq** [comment]
https://github.com/shadowbq/nomnomlog#choosing-app-name

```yaml
files:
  - path: /var/log/httpd/access_log
    tag: apache
```
